# Generated by Django 5.0.3 on 2024-03-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneReview', '0002_brand_model_review_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model_images/'),
        ),
    ]
