# Generated by Django 5.0.3 on 2024-03-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneReview', '0003_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='slug',
            field=models.SlugField(default='null', max_length=150),
        ),
    ]
