# Generated by Django 5.0.3 on 2024-03-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneReview', '0004_model_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='manufacturing_since',
            field=models.DateField(null=True),
        ),
    ]
