# Generated by Django 5.0.3 on 2024-04-01 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneReview', '0005_alter_brand_manufacturing_since'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='models',
            new_name='phone_model',
        ),
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(default='null', max_length=150),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
