# Generated by Django 5.0.3 on 2024-04-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneReview', '0006_rename_models_review_phone_model_review_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='null', max_length=150),
        ),
    ]
